on:
  push:
    # branches:
    # - 'main'
  pull_request:
    types:
      - closed

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/debug-action@v2
    - name: echo merged
      # if: github.event.pull_request.merged == true
      run: |
        echo "github.event.pull_request.merged: ${{ github.event.pull_request.merged }}"
        echo "github.event.pull_request.ref: ${{ github.event.pull_request.ref }}"
        echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
